# see https://invent.kde.org/sysadmin/repo-metadata/-/blob/master/branch-rules.yml
Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kcrash': '@latest-kf6'
    'frameworks/kguiaddons': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kparts': '@latest-kf6'
    'frameworks/kwidgetsaddons': '@latest-kf6'
    'frameworks/kdoctools': '@latest-kf6'
    'frameworks/karchive': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/kitemviews': '@latest-kf6'
    'frameworks/ktexteditor': '@latest-kf6'
    'frameworks/kxmlgui': '@latest-kf6'
    'frameworks/knewstuff': '@latest-kf6'
    'frameworks/kuserfeedback': '@latest-kf6'
    'frameworks/purpose': '@latest-kf6'

Environment:
  KDECI_BUILD: "TRUE"

Options:
  setup-dbus-session: True
  per-test-timeout: 120
  require-passing-tests-on: ['@all']
  cmake-options: '-DLOCAL_DBC_PARSER=ON -DLOCAL_VECTOR_BLF=ON'
