Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kcrash': '@stable'
    'frameworks/kguiaddons': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kparts': '@stable'
    'frameworks/kwidgetsaddons': '@stable'
    'frameworks/kdoctools': '@stable'
    'frameworks/karchive': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/kitemviews': '@stable'
    'frameworks/ktexteditor': '@stable'
    'frameworks/kxmlgui': '@stable'
    'frameworks/knewstuff': '@stable'
    'libraries/kuserfeedback': '@stable'
    'education/cantor': '@stable'
    'qt/qt/qtmqtt': '5.15.2'

Environment:
  KDECI_BUILD: "TRUE"

Options:
  setup-dbus-session: False
  require-passing-tests-on: ['@all']
