#!/bin/bash

BUILDDIR=build

if [ ! -d $BUILDDIR ]; then
	mkdir $BUILDDIR
fi

cd $BUILDDIR

cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-std=c++11 -O2" -DCMAKE_INSTALL_PREFIX=/usr && make -j 4
