#!/bin/bash

BUILDDIR=build-clang

if [ ! -d $BUILDDIR ]; then
	mkdir -p $BUILDDIR
fi

cd $BUILDDIR

export CC=clang
export CXX=clang++

cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr && make -j 4
