#!/bin/bash

BUILDDIR=build_devel

#rm -rf $BUILDDIR

mkdir $BUILDDIR
cd $BUILDDIR

cmake .. -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTS=OFF -DCMAKE_INSTALL_PREFIX=/usr && make -j 4
#cmake .. -DCMAKE_BUILD_TYPE=Debug -DENABLE_LIBCERF=OFF -DCMAKE_INSTALL_PREFIX=/usr && make -j 4
#cmake .. -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTS=OFF -DCMAKE_INSTALL_PREFIX=/usr && make -j 4

#make install
