all : opj2dat liborigin.dll

liborigin.dll : OPJFile.cpp OPJFile.h
	g++ -s -shared OPJFile.cpp -o liborigin.dll -lws2_32 -Wl,--out-implib,liborigin.a

opj2dat: opj2dat.cpp OPJFile.cpp
	g++ -o opj2dat opj2dat.cpp OPJFile.cpp -lws2_32

clean :
	rm -f *~ *.o
