/*
	File                 : WorksheetTest.h
	Project              : LabPlot
	Description          : Tests for Worksheets and positioning them on the plot
	--------------------------------------------------------------------
	SPDX-FileCopyrightText: 2023 Martin Marmsoler <martin.marmsoler@gmail.com>

	SPDX-License-Identifier: GPL-2.0-or-later
*/

#ifndef WORKSHEETELEMENTTEST_H
#define WORKSHEETELEMENTTEST_H

#include "../../CommonTest.h"
#include "helperMacros.h"

class WorksheetElementTest : public CommonTest {
	Q_OBJECT

private Q_SLOTS:
	WORKSHEETELEMENT_TEST_DEFINITION(CustomPoint, WORKSHEETELEMENT_SETPOSITIONLOGICAL);
	WORKSHEETELEMENT_TEST_DEFINITION(CustomPoint, WORKSHEETELEMENT_MOUSE_MOVE);
	WORKSHEETELEMENT_TEST_DEFINITION(CustomPoint, WORKSHEETELEMENT_KEYPRESS_RIGHT);
	WORKSHEETELEMENT_TEST_DEFINITION(CustomPoint, WORKSHEETELEMENT_KEY_PRESSLEFT);
	WORKSHEETELEMENT_TEST_DEFINITION(CustomPoint, WORKSHEETELEMENT_KEYPRESS_UP);
	WORKSHEETELEMENT_TEST_DEFINITION(CustomPoint, WORKSHEETELEMENT_KEYPRESS_DOWN);
	WORKSHEETELEMENT_TEST_DEFINITION(CustomPoint, WORKSHEETELEMENT_ENABLE_DISABLE_COORDBINDING);
	WORKSHEETELEMENT_TEST_DEFINITION(CustomPoint, WORKSHEETELEMENT_SHIFTX_COORDBINDING);
	WORKSHEETELEMENT_TEST_DEFINITION(CustomPoint, WORKSHEETELEMENT_SHIFTY_COORDBINDING);
	WORKSHEETELEMENT_TEST_DEFINITION(CustomPoint, WORKSHEETELEMENT_SHIFTX_NO_COORDBINDING);
	WORKSHEETELEMENT_TEST_DEFINITION(CustomPoint, WORKSHEETELEMENT_SHIFTY_NO_COORDBINDING);

	void referenceRangeXMouseMove();
	void referenceRangeYMouseMove();
};

#endif // WORKSHEETELEMENTTEST_H
