.\" Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.\" Please adjust this date whenever revising the manpage.
.\" 
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.TH "LabPlot" "1" "September 29, 2018" "" ""
.SH "NAME"
LabPlot \- a KDE-application for interactive graphing and analysis of scientific data.
.SH "SYNOPSIS"
.B labplot2
[ \fIgeneric\-options\fP ]
[ \fIfile\fP ... ]



.SH "DESCRIPTION"
\fBLabPlot\fP is a data plotting and analysis tool for the KDE desktop.
.PP 
Its features include 2D and 3D data and function, plotting, easy editing of plots, analysis of data and functions, support for different worksheets using MDI and LabPlot project files.  
.PP 
Note that LabPlot is called using labplot2.
.SH "OPTIONS"
For a full summary of options, run \fIlabplot2 \-\-help\fP.



.SH "SEE ALSO"
Full user documentation is available through the KDE Help Centre.
You can also enter the URL
\fIhelp:/labplot2/\fP
directly into dolphin or you can run
`\fIkhelpcenter help:/labplot2/\fP'
from the command\-line.
.PP 

.SH "AUTHOR"
LabPlot2 was written by Stefan Gerlach <stefan.gerlach@uni.kn>, Alexander Semke <alexander.semke@web.de>, Fábián Kristóf-Szabolcs <f-kristof@hotmail.com> and several other authors.
.br 
This manual page was prepared by Helen Faulkner <helen_ml_faulkner@yahoo.co.uk>
for the Debian GNU/Linux system (but may be used by others).
