//LabPlot : symbols.h
// sync with labplot.qs

#ifndef SYMBOLS_H
#define SYMBOLS_H

// symbol type
#define SYMBOLNR 50
enum SType {SNONE,SCROSS,SDOT,SPLUS,SCIRCLE,STRIANGLE,SUTRIANGLE,SRECT,SSTAR,SDIAMOND,SMINUS,SPIPE,
	SLTRIANGLE,SRTRIANGLE,STRIANGLE1,STRIANGLE2,STRIANGLE3,STRIANGLE4,SUCIRCLE,SDCIRCLE,SSTAR2,
	SVBAR,SHBAR,SDIAG1,SDIAG2,SCROSS2,SDIAG3,SDIAG4,SCROSS3,
	SPARRIGHT,SPARLEFT,SHLEFTCIRCLE,SHRIGHTCIRCLE,SSMALLDIAMOND,SROTDIAMOND,SPENTA,SPENTALEFT,
	SPENTABOTTOM,SPENTARIGHT,SHEXAGON,SVHEXAGON,SSTAR3,SUARROW,SLARROW,SDARROW,SRARROW,
	SUHOUSE,SLHOUSE,SDHOUSE,SRHOUSE};
// symbol fill type 
#define SYMBOLFILLNR 10
enum FType {FNONE,FFULL,FBOTTOM,FTOP,FLEFT,FRIGHT,FURIGHT,FDLEFT,FULEFT,FDRIGHT};

#endif // SYMBOLS_H  
